PART 6 A
========
SELECT * FROM STUDENT

SELECT * FROM RESULT

CREATE TABLE RESULT(
RNO INT,
SPI DECIMAL(8,2))



INSERT INTO RESULT VALUES(101,8.8);
INSERT INTO RESULT VALUES (102,9.2);
INSERT INTO RESULT VALUES(103,7.6);
INSERT INTO RESULT VALUES(104,8.2);
INSERT INTO RESULT VALUES(105,7.0);
INSERT INTO RESULT VALUES(106,8.9);

CREATE TABLE EMPLOYEE (
EMPLOYEENO VARCHAR(10),
NAME VARCHAR(20),
MANAGERNO VARCHAR(10));

SELECT * FROM EMPLOYEE

DROP TABLE EMPLOYEE 

INSERT INTO EMPLOYEE VALUES('E01','TARUN',NULL);
INSERT INTO EMPLOYEE VALUES('E02','ROHAN','E02');
INSERT INTO EMPLOYEE VALUES('E03','PRIYA','E01');
INSERT INTO EMPLOYEE VALUES('E04','MILAN','E03');
INSERT INTO EMPLOYEE VALUES('E05','JAY','E01');
INSERT INTO EMPLOYEE VALUES('E06','ANJANA','E04');
--1--
SELECT * FROM STUDENT CROSS JOIN RESULT
--1--
SELECT * FROM STUDENT S INNER JOIN RESULT R ON S.RNO=R.RNO
--2--
SELECT  S.RNO,NAME,BRANCH,SPI FROM STUDENT S INNER JOIN RESULT R ON S.RNO=R.RNO
--3--
SELECT S.RNO,NAME,BRANCH,SPI FROM STUDENT S INNER JOIN RESULT R ON S.RNO=R.RNO WHERE BRANCH='CE'
--4--
SELECT  S.RNO,NAME,BRANCH,SPI FROM STUDENT S INNER JOIN RESULT R ON S.RNO=R.RNO WHERE BRANCH='EC'
--5--
SELECT s.BRANCH,AVG(r.SPI) AS 'AVG SPI RESULT' FROM STUDENT s INNER JOIN RESULT r ON s.RNO=r.RNO GROUP BY s.BRANCH;
--6--
SELECT s.BRANCH,AVG(r.SPI) AS 'AVG SPI RESULT' FROM STUDENT s INNER JOIN RESULT r ON s.RNO=r.RNO GROUP BY s.BRANCH ORDER BY AVG(r.SPI)
--7--
SELECT s.BRANCH,AVG(r.SPI) AS 'AVG SPI RESULTS' FROM STUDENT s INNER JOIN RESULT r ON s.RNO=r.RNO WHERE s.BRANCH IN('CE','ME') GROUP BY s.BRANCH
--8-- check 
SELECT * FROM STUDENT S LEFT  JOIN RESULT R ON s.RNO=r.RNO
--9-- check 
SELECT * FROM STUDENT S RIGHT JOIN RESULT R ON s.RNO=r.RNO
--10-- check
SELECT * FROM STUDENT S FULL JOIN RESULT R ON s.RNO=r.RNO
--11--
select * from employee
--11--
SELECT E.NAME AS 'EMPLOYEE NAME',F.NAME AS 'MANAGER NAME'
FROM EMPLOYEE1 E INNER JOIN EMPLOYEE1 F
ON E.MANAGERNO=F.EMPLOYEENO
