CREATE TABLE COMPANY (
COM_ID INT,
COM_NAME VARCHAR(50));

INSERT INTO COMPANY VALUES(
11, 'Samsung');

INSERT INTO COMPANY VALUES(12, 'iBall');

INSERT INTO COMPANY VALUES(13, 'Epsion');

INSERT INTO COMPANY VALUES(14, 'Zebronics');

INSERT INTO COMPANY VALUES(15, 'Asus');

INSERT INTO COMPANY VALUES(16, 'Frontech');

SELECT * FROM COMPANY
--------
CREATE TABLE ITEM_MASTER(
PRO_ID INT,
PRO_NAME VARCHAR(50),
PRO_PRICE INT,
PRO_COM INT);

INSERT INTO ITEM_MASTER VALUES(101, 'Mother Board', 3200, 15);

INSERT INTO ITEM_MASTER VALUES(102, 'Key Board', 450, 16);

INSERT INTO ITEM_MASTER VALUES(103, 'ZIP drive', 250, 14);

INSERT INTO ITEM_MASTER VALUES(104, 'Speaker', 550, 16);

INSERT INTO ITEM_MASTER VALUES(105, 'Monitor', 5000, 11);

INSERT INTO ITEM_MASTER VALUES(106, 'DVD drive', 900, 12);

INSERT INTO ITEM_MASTER VALUES(107, 'CD drive', 800, 12);

INSERT INTO ITEM_MASTER VALUES(108, 'Printer', 2600, 13);

INSERT INTO ITEM_MASTER VALUES(109, 'Refill cartridge', 350, 13);

INSERT INTO ITEM_MASTER VALUES(110, 'Mouse', 250, 12);

SELECT * FROM ITEM_MASTER
-----------
CREATE TABLE EMP_DETAILS(
EMP_IDNO  INT,
EMP_FNAME VARCHAR(50),
EMP_DNAME VARCHAR(50),
EMP_DEPT INT);

INSERT INTO EMP_DETAILS VALUES (127323, 'Michale', 'Robbin', 57);

INSERT INTO EMP_DETAILS VALUES(526689, 'Carlos', 'Snares', 63);

INSERT INTO EMP_DETAILS VALUES(843795, 'Enric', 'Dosio', 57);

INSERT INTO EMP_DETAILS VALUES(328717, 'Jhon', 'Snares', 63);

INSERT INTO EMP_DETAILS VALUES(444527, 'Joseph', 'Dosni', 47);

INSERT INTO EMP_DETAILS VALUES(659831, 'Zanifer', 'Emily', 47);

INSERT INTO EMP_DETAILS VALUES(847674, 'Kuleswar', 'Sitaraman', 57);

INSERT INTO EMP_DETAILS VALUES(748681, 'Henrey', 'Gabriel', 47);

INSERT INTO EMP_DETAILS VALUES(555935, 'Alex', 'Manuel', 57);

INSERT INTO EMP_DETAILS VALUES(539569, 'George', 'Mardy', 27);

INSERT INTO EMP_DETAILS VALUES(733843, 'Mario', 'Saule', 63);

INSERT INTO EMP_DETAILS VALUES(631548, 'Alan', 'Snappy', 27);

INSERT INTO EMP_DETAILS VALUES(839139, 'Maria', 'Foster', 57);

SELECT * FROM EMP_DETAILS
----------

CREATE TABLE EMP_DEPARTMENT(DPT_CODE INT,
DPT_NAME VARCHAR(50),
DPT_ALLOTMENT INT);

SELECT * FROM EMP_DEPARTMENT

INSERT INTO EMP_DEPARTMENT VALUES(57, 'IT', 65000);

INSERT INTO EMP_DEPARTMENT VALUES(63, 'Finance', 15000);

INSERT INTO EMP_DEPARTMENT VALUES(47, 'HR', 240000);

INSERT INTO EMP_DEPARTMENT VALUES(27, 'RD', 55000);

INSERT INTO EMP_DEPARTMENT VALUES(89, 'QC', 75000);
-----
SELECT * FROM COMPANY 
SELECT * FROM ITEM_MASTER
SELECT * FROM EMP_DETAILS
SELECT * FROM EMP_DEPARTMENT
--1--
SELECT AVG(PRO_PRICE)AS 'AVERAGE PRICE',COM_NAME 
FROM ITEM_MASTER I 
INNER JOIN COMPANY C O
N I.PRO_COM=COM_ID 
GROUP BY COM_NAME
--2--
SELECT AVG(PRO_PRICE)AS 'AVERAGE PRICE',COM_NAME 
FROM ITEM_MASTER I 
INNER JOIN COMPANY C 
ON I.PRO_COM=COM_ID 
GROUP BY COM_NAME 
HAVING AVG(PRO_PRICE)>350
--3--
SELECT PRO_NAME,MAX(PRO_PRICE)AS 'MAXIMUM PRICE',COM_NAME 
FROM ITEM_MASTER I 
INNER JOIN COMPANY C 
ON I.PRO_COM=COM_ID 
GROUP BY COM_NAME
--4--
SELECT * FROM EMP_DETAILS 
WHERE EMP_DNAME = 'GABRIEL' OR  EMP_DNAME ='DOSIO'
--5--department 89 or 63
SELECT * FROM EMP_DETAILS 
WHERE EMP_DEPT = 89 OR EMP_DEPT = 63
