select * from emp_details
select * from emp_department
--C--1--
SELECT EMP_FNAME,EMP_DNAME
FROM EMP_DETAILS E INNER JOIN EMP_DEPARTMENT ED 
ON E.EMP_DEPT = ED.DPT_CODE 
WHERE DPT_ALLOTMENT>50000
--2--
SELECT * FROM EMP_DEPARTMENT 
WHERE DPT_ALLOTMENT > (SELECT AVG(DPT_ALLOTMENT) 
FROM EMP_DEPARTMENT);
--3--
SELECT DPT_NAME, COUNT(EMP_DEPT)AS 'NO. OF EMPLOYEES'
FROM EMP_DEPARTMENT
INNER JOIN EMP_DETAILS 
ON DPT_CODE = EMP_DEPT
GROUP BY DPT_NAME 
HAVING COUNT(EMP_DEPT) > 2
--4--
SELECT EMP_FNAME,EMP_DNAME 
FROM EMP_DETAILS  
INNER JOIN EMP_DEPARTMENT
ON EMP_DEPT = DPT_CODE
WHERE DPT_ALLOTMENT = (SELECT DPT_ALLOTMENT FROM EMP_DEPARTMENT ORDER BY DPT_ALLOTMENT  LIMIT 1 OFFSET 1)
