CREATE TABLE STUDENT(
RNO INT,
NAME VARCHAR(50),
CITY VARCHAR(50),
DID INT);

INSERT INTO STUDENT VALUES(
101, 'Raju', 'Rajkot', 10);

INSERT INTO STUDENT VALUES(102, 'Amit', 'Ahmedabad', 20);

INSERT INTO STUDENT VALUES(103, 'Sanjay', 'Baroda', 40);

INSERT INTO STUDENT VALUES(104, 'Neha', 'Rajkot', 20);

INSERT INTO STUDENT VALUES(105, 'Meera', 'Ahmedabad', 30);

INSERT INTO STUDENT VALUES(106, 'Mahesh', 'Baroda',10);

SELECT * FROM STUDENT
CREATE TABLE ACADEMIC(
RNO INT,
SPI DECINAL(8,2),
BACKLOG INT);

INSERT INTO ACADEMIC VALUES(101, 8.8, 0);

INSERT INTO ACADEMIC VALUES(102, 9.2, 2);

INSERT INTO ACADEMIC VALUES(103, 7.6, 1);

INSERT INTO ACADEMIC VALUES(104, 8.2, 4);

INSERT INTO ACADEMIC VALUES(105, 7.0, 2);

INSERT INTO ACADEMIC VALUES(106, 8.9, 3);

SELECT * FROM ACADEMIC

CREATE TABLE DEPARTMENT(
DID INT,
DNAME VARCHAR);

INSERT INTO DEPARTMENT VALUES(10, 'Computer');

INSERT INTO DEPARTMENT VALUES(20, 'Electrical');

INSERT INTO DEPARTMENT VALUES(30, 'Mechanical');

INSERT INTO DEPARTMENT VALUES(40, 'Civil');

SELECT * FROM DEPARTMENT

--1--
SELECT S.NAME, D.DNAME 
FROM STUDENT S 
INNER JOIN DEPARTMENT D ON S.DID = D.DID 
WHERE D.DNAME = 'COMPUTER';
--2--
SELECT S.NAME,A.SPI FROM STUDENT S INNER JOIN ACADEMIC A ON S.RNO=A.RNO WHERE A.SPI>8;

--3--
SELECT S.NAME, D.DNAME 
FROM STUDENT S 
INNER JOIN DEPARTMENT D ON S.DID = D.DID 
WHERE D.DNAME = 'COMPUTER'
GROUP BY S.NAME HAVING S.CITY = 'Rajkot'
--4--
SELECT COUNT(*)AS 'TOTAL NO. OF STUDENT',DNAME FROM STUDENT S INNER JOIN DEPARTMENT D ON S.DID = D.DID WHERE D.DNAME = 'ELECTRICAL'; 
--5--
SELECT S.NAME,A.SPI FROM STUDENT S INNER JOIN ACADEMIC A ON S.RNO = A.RNO WHERE A.SPI = (SELECT MAX(SPI) FROM ACADEMIC);
--6--	
SELECT NAME,BACKLOG FROM STUDENT S INNER JOIN ACADEMIC A ON S.RNO=A.RNO WHERE BACKLOG>1;
--7--
SELECT NAME,A.SPI FROM STUDENT S INNER JOIN ACADEMIC A ON S.RNO=A.RNO WHERE A.SPI = (SELECT SPI FROM ACADEMIC ORDER BY SPI DESC  LIMIT 1 OFFSET 1);
--8--
SELECT NAME,DNAME FROM STUDENT S INNER JOIN DEPARTMENT D ON S.DID=D.DID WHERE DNAME = 'computer' OR DNAME='MECHANICAL'
--9--
SELECT NAME,DNAME FROM STUDENT S INNER JOIN DEPARTMENT D ON S.DID=D.DID WHERE D.DNAME = (SELECT DNAME FROM DEPARTMENT D INNER JOIN STUDENT S ON D.DID=S.DID WHERE S.RNO=102)
--10--
SELECT S.NAME,D.DNAME FROM STUDENT S INNER JOIN DEPARTMENT D ON S.DID=D.DID INNER JOIN ACADEMIC A ON S.RNO=A.RNO WHERE SPI>9 AND D.DNAME='ELECTRICAL'


