--5(B)--

SELECT * FROM ORDERS 
SELECT * FROM SALESMAN 
--5(B)--
--1--
SELECT SALESMAN_ID,MAX(PUCH_AMT) AS 'HIGHEST PURCHASE ' FROM ORDERS GROUP BY SALESMAN_ID HAVING ORD_DATE='17-AUG-2012'
--2--
SELECT  CUSTOMER_ID,ORD_DATE,MAX(PUCH_AMT) AS 'HIGHEST PURCHASE' FROM ORDERS GROUP BY CUSTOMER_ID,ORD_DATE HAVING MAX(PUCH_AMT)>2000
--3--
SELECT CUSTOMER_ID,ORD_DATE,MAX(PUCH_AMT) AS 'HIGHEST PURCHASE' FROM ORDERS GROUP BY CUSTOMER_ID,ORD_DATE HAVING MAX(PUCH_AMT)>=2000 AND MAX(PUCH_AMT)<=6000
--4--
SELECT CUSTOMER_ID,ORD_DATE,MAX(PUCH_AMT) AS 'HIGHEST PURCHASE' FROM ORDERS GROUP BY CUSTOMER_ID,ORD_DATE HAVING MAX(PUCH_AMT) IN (2000, 3000, 5760, 6000)
--5--
SELECT CUSTOMER_ID,MAX(PUCH_AMT) AS 'HIGHEST PURCHASE' FROM ORDERS GROUP BY CUSTOMER_ID HAVING CUSTOMER_ID>=3002 AND CUSTOMER_ID<=3007
--6--
SELECT CUSTOMER_ID,MAX(PUCH_AMT) AS 'HIGHEST PURCHASE' FROM ORDERS WHERE CUSTOMER_ID BETWEEN 3002 AND 3007 GROUP BY CUSTOMER_ID HAVING MAX(PUCH_AMT)>1000
--7--
SELECT SALESMAN_ID,MAX(PUCH_AMT) AS 'HIGHEST PURCHASE' FROM ORDERS GROUP BY SALESMAN_ID HAVING SALESMAN_ID>=5003 AND SALESMAN_ID<=5008
--8--
SELECT ORD_NO FROM ORDERS WHERE ORD_DATE='17-AUG-2012'
--9--
SELECT COUNT(*) AS 'NO. OF SALESMAN' FROM SALESMAN 
--10--
SELECT ORD_DATE,SALESMAN_ID,COUNT(*) AS 'NO. OF ORDERS' FROM ORDERS GROUP BY ORD_DATE,SALESMAN_ID
